### ISSUE TITLE
Dosent work at the moment.

### ISSUE THREAD

**Issue by JuXReal** [JuXReal/SimpleDocumentManagement#1]
At the moment, i dont know how to setup crojobs via shell. 

I search for a solution.

**Comment by pickfire** [comment]
Take a look at the Raspberry Pi Documentation:
https://github.com/raspberrypi/documentation/blob/master/linux/usage/cron.md

What does the simple document management do? Why is screen required?

**Comment by JuXReal** [comment]
Good point, i update the READ.Me fast as possible

**Comment by JuXReal** [comment]
Now it works\* - Thank you
