### ISSUE TITLE
No need of the GUI to set up recoll

### ISSUE THREAD

**Issue by ghost** [JuXReal/SimpleDocumentManagement#2]
Hi,

Just FYI, there is no need to use the recoll GUI to set up indexing. After recoll installation, just create the `~/.recoll` directory and add the following line to `~/.recoll/recoll.conf`:

```
topdirs = /path/to/my/doc/directory
```

Then just run recollindex after generating the pdfs, it should exclusively process the designated directory.

**Comment by JuXReal** [comment]
Thank you! I will update my script soon as possible.

**Comment by JuXReal** [comment]
Now implemented. Thank you!
