### ISSUE TITLE
Known issus [need Help]

### ISSUE THREAD

**Issue by JuXReal** [JuXReal/SimpleDocumentManagement#3]
- there ist a Problem with the scripts in /bin . The scripts has no permission to work with the Files in the Folders. But i dont know the right permissions ( with sudo all works fine ).
- Cronjobs doesent start.

**Comment by flakeshake** [comment]
Hello ,
which of those issues still exist ? If the answer is both , can i open a seperate Github issue for
the cronjob problem ?

Greetings ,
Dennis

**Comment by JuXReal** [comment]
Good morning from Germany again.

At the moment, i have two problems.
there ist a Problem with the scripts in /bin . The scripts has no permission to work with the Files in the Folders. But i dont know the right permissions ( with sudo all works fine ).

./run.sh: 39: ../contrib/config.sh: /home/pi/SimpleDocumentManagement/recoll-webui: Permission denied
-   One cronjob is not create right.
  echo $sdm_cron3  $myIP -p 8080 >> oldcrontab

i dont know, how to set right the ""  ( first Time Bash scripting :-/ , and first GitHub :-) )
- Cronjobs doesent start or the scripts doesent start. i cant figur out .-/

**Comment by flakeshake** [comment]
Gehe ich richtig in der Vermutung , dass die Scripts seit vorletztem Sonntag (dem 15.)  richtig laufen ?

**Comment by JuXReal** [comment]
Hallo flakeshake, danke das Du dich noch einmal hier meldest.

Leider läuft es immer noch nicht richtig.
- Das IF Statement für Samba funktioniert noch nicht, da finde ich aber den Fehler nicht.
- Die Cronjobs werden richtig angelegt ( Vielen DANK!!!! ), aber sie werden nicht ausgeführt.

Meine erste Vermutung:

Die Berechtigungen sind noch nicht richtig. ich führe das Script. SDM.sh mit sudo aus. 

Also bedeutet das wohl, das alle Ordner einen falschen User haben. Ich habe es also zum testen von Hand geändert zu Hause, aber es hat nicht geholfen.

Wenn ich die run.sh ausführe ( ohne Sudo ) gibt es noch ein permission denied.

Leider bin ich die letzte (?) Woche auch nicht mehr weiter dazu gekommen.

Falls Du mir also noch einmal helfen würdest währe das super. 

MFG
Sascha
