### ISSUE TITLE
cronjob number 3 does not work

### ISSUE THREAD

**Issue by flakeshake** [JuXReal/SimpleDocumentManagement#6]
As discussed previously in #3. My idea :

In config.sh  , do this

``` bash
sdm_cron3="@reboot screen -dmS RecollWebGui bash -c \"cd $sdm_path/recoll-webui && ./webui-standalone.py -a"
```

(Backslash to escape the double quote)

In SDM.sh , do this 

``` bash
echo "$sdm_cron3 $myIP -p 8080\" "  >> oldcrontab
```

Again , use a backslash to escape the double quote.

This should give the desired result (works for me). I will bundle the changes as PR if you wish.

BTW , do you prefer German ? I wouldn't mind using either language here :grinning: 

Greetings ,
Dennis

**Comment by JuXReal** [comment]
Hi, 
danke für die Hinweise. Ich werde es die Tage umsetzen. 

PR = Pull Request ?
Ich habe natürlich nichts dagegen wenn Du mit hilfst das das Script läuft.

**Comment by flakeshake** [comment]
PR #7 gesendet

**Comment by JuXReal** [comment]
Vielen Dank, die Cronjbs werden nun richtig angelegt. 

Das IF Statement für Samba funktioniert noch nicht, da finde ich aber den Fehler nicht.

Aber soweit sieht es gut aus. Vielen Dank
